language: python
python:
- '3.6'
install:
  - pip install pipenv
  - pipenv install --system
script:
  nosetests
deploy:
- provider: s3
  access_key_id: AKIAJVBBNDHYSNFIIJVA
  secret_access_key: &1
    secure: BmkDRanBXRjqOQfCEEP8l/JZvHrVQ4UXHc/XaCsZLZNeNr1VrtfLrR8En8wS+QNzK2eQMcIvq3cJGFJbPz2zbirBHDRIKUP6WmBMx97toUYoEz2AqWolxP4FzDM0SLSTknEhkoLHDPj5xiJed5Cng1NJJY7RZ4E7UMxuk0CEHYxR2DOO7ssQa+uwttxiKyVTdiY4OcEZCra4Qljz+M2sZMFDV7kEv+dhLLN+BpxoR2s7wuX939cAofr3qX/8sID1RFW5o1t8VAVmnj2P4YD6CoqKujDQ4Ta0RwcZWUFvjCzm70t9vnXSraEZniNJYrc+6RJjICfusKtbFvxbEOt7OT7qhQ/LKxJsWrNwVqwXBb9/7pUOTq88qoRGA90mPvt7+AeI27udMiAkTAYtmFMu7TDe7V4DnVox54JRlgAGyA2nOM7xvO3ClKqMpIHuTIbz9E5AB2jznqhbsUKbzXwB8LHHiQQUxp7r3a8krf525QcR4/3G3zqOrHjM5M1zzY5UlLtYSp4vrl87uAumsiC68Zun5prSUpvK95fiudCBFZC2vzAe9USw8ymcJfsnYkch4PlfMn8rirbnv8I9JFv3zUCHY7w1QC+J7yS5XIbv071XvtZye119WmcGv0KLj0yiTmG4WmK79kERcfmIg1/1Jz9VEE2qwhb/s+rgB/jG7O4=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: alphanexustech/nexus-scorer
    branch: develop
  bucket: nexus-scorer-bucket
- provider: codedeploy
  access_key_id: AKIAJVBBNDHYSNFIIJVA
  secret_access_key: *1
  bucket: nexus-scorer-bucket
  key: latest-lg.zip
  bundle_type: zip
  application: nexus-scorer
  deployment_group: affect-nexus-group
  on: *2
before_deploy:
- zip -r latest-lg Affect.R-Emotion.I-Emotion/* app/* mongo_database_backup/* scripts/* .gitignore .travis.yml appspec.yml LICENSE Pipfile Pipfile.lock README.md
- mkdir -p dpl_cd_upload
- mv latest-lg.zip dpl_cd_upload/latest-lg.zip
